### ISSUE TITLE
Error reading wave file: Expected "[", got "RIFFXS

### ISSUE THREAD

**Issue by shamidreza** [wnhsu/FactorizedHierarchicalVAE#2]
I am facing an error when running the TIMIT example: 
`./run_fhvae.sh --TIMIT_RAW_DATA ~/TIMIT/TIMIT --stage -1`

It seems that the code expects "[" but the audio file header is "RIFF" type.
**ERROR (Read():kaldi-matrix.cc:1432) Failed to read matrix from stream.  : Expected "[", got "RIFFXS**

Here is the full log:
```
Loading datasets: train=True, dev=True, test=False
KaldiRADataset constructor
ERROR (Read():kaldi-matrix.cc:1432) Failed to read matrix from stream.  : Expected "[", got "RIFFXS
WARNING (Read():util/kaldi-holder-inl.h:82) Exception caught reading Table object 
WARNING (LoadCurrent():util/kaldi-table-inl.h:246) TableReader: failed to load object from /home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/data/wav/train/FAEM0_SI1392.wav
ERROR (Value():util/kaldi-table-inl.h:149) TableReader: failed to load object from /home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/data/wav/train/FAEM0_SI1392.wav (to suppress this error, add the permissive (p, ) option to the rspecifier.
Traceback (most recent call last):
  File "src/scripts/run_nips17_fhvae_exp.py", line 500, in <module>
    main()
  File "src/scripts/run_nips17_fhvae_exp.py", line 115, in main
    set_name, is_train, True, True, False)
  File "src/scripts/run_nips17_fhvae_exp.py", line 342, in _load_datasets_and_model
    sets = datasets_loader(dataset_conf, train, dev, test)
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/datasets_loaders.py", line 45, in datasets_loader
    return kaldi_ra_datasets_loader(conf, train, dev, test)
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/datasets_loaders.py", line 55, in kaldi_ra_datasets_loader
    return _kaldi_ra_datasets_loader(Dataset, conf, train, dev, test)
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/datasets_loaders.py", line 117, in _kaldi_ra_datasets_loader
    q_type=q_type)
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/kaldi_ra_dataset.py", line 81, in __init__
    super(KaldiRADataset, self).__init__(**kwargs)
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/base_dataset.py", line 14, in __init__
    self._load_data()
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/kaldi_ra_dataset.py", line 112, in _load_data
    self._load_kaldi_feat_list()
  File "/home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/src/datasets/kaldi_ra_dataset.py", line 126, in _load_kaldi_feat_list
    utt_id, utt_feats = f.next()
RuntimeError: ERROR (Value():util/kaldi-table-inl.h:149) TableReader: failed to load object from /home/hamid/VAE/FactorizedHierarchicalVAE/egs/timit/data/wav/train/FAEM0_SI1392.wav (to suppress this error, add the permissive (p, ) option to the rspecifier.

[stack trace: ]
kaldi::KaldiGetStackTrace()
kaldi::KaldiErrorMessage::~KaldiErrorMessage()
kaldi::SequentialTableReaderScriptImpl<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >::Value()
kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >::Value()
boost::python::api::object sequential_reader_next<kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > > >(kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&)
_object* boost::python::detail::invoke<boost::python::to_python_value<boost::python::api::object const&>, boost::python::api::object (*)(kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&), boost::python::arg_from_python<kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&> >(boost::python::detail::invoke_tag_<false, false>, boost::python::to_python_value<boost::python::api::object const&> const&, boost::python::api::object (*&)(kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&), boost::python::arg_from_python<kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&>&)
boost::python::detail::caller_arity<1u>::impl<boost::python::api::object (*)(kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&), boost::python::default_call_policies, boost::mpl::vector2<boost::python::api::object, kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&> >::operator()(_object*, _object*)
boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::python::api::object (*)(kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&), boost::python::default_call_policies, boost::mpl::vector2<boost::python::api::object, kaldi::SequentialTableReader<PythonToKaldiHolder<MatrixToNdArrayConverter<float> > >&> > >::operator()(_object*, _object*)
boost::python::objects::function::call(_object*, _object*) const
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0(+0x279b8) [0x7f36f68629b8]
.
.
.
python(PyEval_EvalFrameEx+0x7e8) [0x524338]
python(PyEval_EvalFrameEx+0xc9a) [0x5247ea]
python(PyEval_EvalCodeEx+0x2b1) [0x555551]
python(PyEval_EvalFrameEx+0x1a10) [0x525560]
python() [0x567d14]
python(PyRun_FileExFlags+0x92) [0x465bf4]
python(PyRun_SimpleFileExFlags+0x2ee) [0x46612d]
python(Py_Main+0xb5e) [0x466d92]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f373d1daf45]
python() [0x577c2e]

```

**Comment by shamidreza** [comment]
FYI, I started from a fresh installation and this error did not happen again. Do not exactly know the reason for the initial error.

**Comment by wnhsu** [comment]
seems to be Kaldi's installation problem. I did notice Kaldi had changed data I/O format at least once. Installing according to the instructions in README.md would be crucial.

I will close this issue for now. Please let me know if the problem occurs again. Thanks

**Comment by kvvaldez** [comment]
the path of the  Kaldi was probably renamed or changed
